Update to fastdds 3.1

diff --git a/external/fastddsgen/fastddsgen b/external/fastddsgen/fastddsgen
--- a/external/fastddsgen/fastddsgen
+++ b/external/fastddsgen/fastddsgen
@@ -2,13 +2,18 @@
 
 dir="`dirname \"$0\"`"
 
-java_exec=java
+java_exec="${JAVA_HOME}/bin/java"
 
-java -version &>/dev/null
+${java_exec} -version &>/dev/null
 
 if [ $? != 0 ]; then
-    [ -z "$JAVA_HOME" ] && { echo "Java binary cannot be found. Please, make sure its location is in the PATH environment variable or set JAVA_HOME environment variable."; exit 1; }
-    java_exec="${JAVA_HOME}/bin/java"
+    java_exec=java
+fi
+
+${java_exec} -version &>/dev/null
+if [ $? != 0 ]; then
+    echo "Java binary cannot be found. Please, make sure its location is in the PATH environment variable or set JAVA_HOME environment variable."; 
+    exit 1;     
 fi
 
 exec $java_exec -jar "$dir/fastddsgen.jar" "$@"
